name: build-and-release-pipeline
on: 
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - v*
jobs:
  test-restservice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.4'
      - name: Build RestService
        run: go build
        working-directory: ./src/restService
      # - uses: actions/checkout@v2
      # - name: Run Unit Tests
      #   run: go test

  build-webapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: echo $(pwd)
      - name: Setup NodeJS
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
        working-directory: ./src/webapp
      - name: Build WebApp
        run: npm run build
        working-directory: ./src/webapp
      - name: Package build
        run: tar zcf webapp-package.tar.gz *
        working-directory: ./src/webapp/dist
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp-package
          path: ./src/webapp/dist/webapp-package.tar.gz
          retention-days: 7
      
  release-dev:
    runs-on: ubuntu-latest
    needs: [test-restservice, build-webapp]
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Extract Version
        id: version_step
        run: |
          echo "version_tag=ghcr.io/mstraubac/smarthomerestapp_restservice:$(echo ${{ github.actor }}_dev | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Print Version
        run: |
          echo ${{ env.version_tag }}
          echo ${{ github.actor }}
      - name: Fetch webapp-package artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp-package
      - run: ls -l /home/runner/work/smarthomeRESTApp/smarthomeRESTApp/
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build Container Image
        run: docker build . --tag ghcr.io/mstraubac/smarthomerestapp_restservice:${{ env.version_tag }}
        working-directory: ./src/restService
      - name: Push Container Image to registry
        run: docker push ghcr.io/mstraubac/smarthomerestapp_restservice:${{ env.version_tag }}
        working-directory: ./src/restService

  release-stable:
    runs-on: ubuntu-latest
    needs: [test-restservice, build-webapp]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Extract Version
        id: version_step
        run: |
          echo "version=${GITHUB_REF#$"refs/tags/v"}" >> $GITHUB_OUTPUT
          echo "version_tag=ghcr.io/mstraubac/smarthomerestapp_restservice:${GITHUB_REF#$"refs/tags/v"}" >> $GITHUB_ENV
          echo "latest_tag=ghcr.io/mstraubac/smarthomerestapp_restservice:latest" >> $GITHUB_ENV
      - name: Print Version
        run: |
          echo ${{steps.version_step.outputs.version_tag}}
          echo ${{steps.version_step.outputs.latest_tag}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build Container Image
        run: docker build . --tag ${{ env.latest_tag }} --tag ${{ env.version_tag }}
        working-directory: ./src/restService
      - name: Push Container Image to registry
        run: docker push --all-tags ${{ env.latest_tag }}
        working-directory: ./src/restService